---
- name: Install sysstat
  yum:
    name: sysstat
    state: present
    validate_certs: yes
  become: yes

- name: Set interval for sysstat
  copy:
    dest: /etc/cron.d/sysstat
    content: |
      # Run system activity accounting tool every {{ sysstat.interval }} minutes
      */{{ sysstat.interval }} * * * * root /usr/lib64/sa/sa1 1 1
      # 0 * * * * root /usr/lib64/sa/sa1 600 6 &
      # Generate a daily summary of process accounting at 23:{{ sysstat.summary_minute }}
      {{ sysstat.summary_minute }} 23 * * * root /usr/lib64/sa/sa2 -A
  become: yes

- name: Enable sysstat
  service:
    name: sysstat
    state: started
    enabled: yes
  become: yes
